"""init

Revision ID: cd786a6033f6
Revises: 
Create Date: 2025-12-14 21:49:44.777717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd786a6033f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_status'), 'event_outbox', ['status'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_project_id'), 'resources', ['project_id'], unique=False)
    op.create_table('revoke_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_account_id', sa.UUID(), nullable=False),
    sa.Column('requester_uuid', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoke_requests_access_account_id'), 'revoke_requests', ['access_account_id'], unique=False)
    op.create_index(op.f('ix_revoke_requests_requester_uuid'), 'revoke_requests', ['requester_uuid'], unique=False)
    op.create_table('access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('requester_uuid', sa.UUID(), nullable=False),
    sa.Column('request_name', sa.String(length=200), nullable=False),
    sa.Column('ttl_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_uuid', sa.UUID(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_requester_uuid'), 'access_requests', ['requester_uuid'], unique=False)
    op.create_index(op.f('ix_access_requests_resource_id'), 'access_requests', ['resource_id'], unique=False)
    op.create_index(op.f('ix_access_requests_reviewer_uuid'), 'access_requests', ['reviewer_uuid'], unique=False)
    op.create_table('access_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_request_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['access_request_id'], ['access_requests.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_accounts_granted_by'), 'access_accounts', ['granted_by'], unique=False)
    op.create_index(op.f('ix_access_accounts_is_active'), 'access_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_access_accounts_resource_id'), 'access_accounts', ['resource_id'], unique=False)
    op.create_index(op.f('ix_access_accounts_user_uuid'), 'access_accounts', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_accounts_user_uuid'), table_name='access_accounts')
    op.drop_index(op.f('ix_access_accounts_resource_id'), table_name='access_accounts')
    op.drop_index(op.f('ix_access_accounts_is_active'), table_name='access_accounts')
    op.drop_index(op.f('ix_access_accounts_granted_by'), table_name='access_accounts')
    op.drop_table('access_accounts')
    op.drop_index(op.f('ix_access_requests_reviewer_uuid'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_resource_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_requester_uuid'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_revoke_requests_requester_uuid'), table_name='revoke_requests')
    op.drop_index(op.f('ix_revoke_requests_access_account_id'), table_name='revoke_requests')
    op.drop_table('revoke_requests')
    op.drop_index(op.f('ix_resources_project_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_event_outbox_status'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
