class ResourceProviderException(Exception): ...


class ResourceNotAvailableException(ResourceProviderException): ...


class ResourceUserConfigNotFound(ResourceNotAvailableException): ...


class ResourceProviderNotExists(ResourceProviderException): ...
