# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from services.secret_service.protobuf import secret_service_pb2 as secret__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in secret_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecretStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitStorage = channel.unary_unary(
            '/secret_service.v1.SecretStore/InitStorage',
            request_serializer=secret__service__pb2.InitStorageRequest.SerializeToString,
            response_deserializer=secret__service__pb2.InitStorageResponse.FromString,
            _registered_method=True,
        )
        self.Unseal = channel.unary_unary(
            '/secret_service.v1.SecretStore/Unseal',
            request_serializer=secret__service__pb2.UnsealRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.Seal = channel.unary_unary(
            '/secret_service.v1.SecretStore/Seal',
            request_serializer=secret__service__pb2.SealRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.PutSecret = channel.unary_unary(
            '/secret_service.v1.SecretStore/PutSecret',
            request_serializer=secret__service__pb2.PutSecretRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.GetSecret = channel.unary_unary(
            '/secret_service.v1.SecretStore/GetSecret',
            request_serializer=secret__service__pb2.GetSecretRequest.SerializeToString,
            response_deserializer=secret__service__pb2.GetSecretResponse.FromString,
            _registered_method=True,
        )
        self.DeleteSecret = channel.unary_unary(
            '/secret_service.v1.SecretStore/DeleteSecret',
            request_serializer=secret__service__pb2.DeleteSecretRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )


class SecretStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unseal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'InitStorage': grpc.unary_unary_rpc_method_handler(
            servicer.InitStorage,
            request_deserializer=secret__service__pb2.InitStorageRequest.FromString,
            response_serializer=secret__service__pb2.InitStorageResponse.SerializeToString,
        ),
        'Unseal': grpc.unary_unary_rpc_method_handler(
            servicer.Unseal,
            request_deserializer=secret__service__pb2.UnsealRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'Seal': grpc.unary_unary_rpc_method_handler(
            servicer.Seal,
            request_deserializer=secret__service__pb2.SealRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'PutSecret': grpc.unary_unary_rpc_method_handler(
            servicer.PutSecret,
            request_deserializer=secret__service__pb2.PutSecretRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'GetSecret': grpc.unary_unary_rpc_method_handler(
            servicer.GetSecret,
            request_deserializer=secret__service__pb2.GetSecretRequest.FromString,
            response_serializer=secret__service__pb2.GetSecretResponse.SerializeToString,
        ),
        'DeleteSecret': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSecret,
            request_deserializer=secret__service__pb2.DeleteSecretRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('secret_service.v1.SecretStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secret_service.v1.SecretStore', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SecretStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitStorage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secret_service.v1.SecretStore/InitStorage',
            secret__service__pb2.InitStorageRequest.SerializeToString,
            secret__service__pb2.InitStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Unseal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secret_service.v1.SecretStore/Unseal',
            secret__service__pb2.UnsealRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Seal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secret_service.v1.SecretStore/Seal',
            secret__service__pb2.SealRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PutSecret(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secret_service.v1.SecretStore/PutSecret',
            secret__service__pb2.PutSecretRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSecret(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secret_service.v1.SecretStore/GetSecret',
            secret__service__pb2.GetSecretRequest.SerializeToString,
            secret__service__pb2.GetSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteSecret(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secret_service.v1.SecretStore/DeleteSecret',
            secret__service__pb2.DeleteSecretRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
