# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: secret_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'secret_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14secret_service.proto\x12\x11secret_service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"7\n\x12InitStorageRequest\x12\x0e\n\x06shares\x18\x01 \x01(\x05\x12\x11\n\tthreshold\x18\x02 \x01(\x05\"%\n\x13InitStorageResponse\x12\x0e\n\x06shares\x18\x01 \x03(\t\"\x1f\n\rUnsealRequest\x12\x0e\n\x06shares\x18\x02 \x03(\t\"\r\n\x0bSealRequest\"\xa3\x01\n\x10PutSecretRequest\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x12\n\njson_value\x18\x02 \x01(\t\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x08metadata\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x12\n\nif_version\x18\x05 \x01(\x03\" \n\x10GetSecretRequest\x12\x0c\n\x04path\x18\x01 \x03(\t\"\xf3\x01\n\x11GetSecretResponse\x12\x12\n\njson_value\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07version\x18\x05 \x01(\x03\x12)\n\x08metadata\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\"7\n\x13\x44\x65leteSecretRequest\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x12\n\nif_version\x18\x03 \x01(\x03\x32\xe1\x03\n\x0bSecretStore\x12\\\n\x0bInitStorage\x12%.secret_service.v1.InitStorageRequest\x1a&.secret_service.v1.InitStorageResponse\x12\x42\n\x06Unseal\x12 .secret_service.v1.UnsealRequest\x1a\x16.google.protobuf.Empty\x12>\n\x04Seal\x12\x1e.secret_service.v1.SealRequest\x1a\x16.google.protobuf.Empty\x12H\n\tPutSecret\x12#.secret_service.v1.PutSecretRequest\x1a\x16.google.protobuf.Empty\x12V\n\tGetSecret\x12#.secret_service.v1.GetSecretRequest\x1a$.secret_service.v1.GetSecretResponse\x12N\n\x0c\x44\x65leteSecret\x12&.secret_service.v1.DeleteSecretRequest\x1a\x16.google.protobuf.EmptyB=Z;github.com/access-core-tech/watchflow/api/secret_service/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secret_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/access-core-tech/watchflow/api/secret_service/v1'
  _globals['_INITSTORAGEREQUEST']._serialized_start=135
  _globals['_INITSTORAGEREQUEST']._serialized_end=190
  _globals['_INITSTORAGERESPONSE']._serialized_start=192
  _globals['_INITSTORAGERESPONSE']._serialized_end=229
  _globals['_UNSEALREQUEST']._serialized_start=231
  _globals['_UNSEALREQUEST']._serialized_end=262
  _globals['_SEALREQUEST']._serialized_start=264
  _globals['_SEALREQUEST']._serialized_end=277
  _globals['_PUTSECRETREQUEST']._serialized_start=280
  _globals['_PUTSECRETREQUEST']._serialized_end=443
  _globals['_GETSECRETREQUEST']._serialized_start=445
  _globals['_GETSECRETREQUEST']._serialized_end=477
  _globals['_GETSECRETRESPONSE']._serialized_start=480
  _globals['_GETSECRETRESPONSE']._serialized_end=723
  _globals['_DELETESECRETREQUEST']._serialized_start=725
  _globals['_DELETESECRETREQUEST']._serialized_end=780
  _globals['_SECRETSTORE']._serialized_start=783
  _globals['_SECRETSTORE']._serialized_end=1264
# @@protoc_insertion_point(module_scope)
