# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fast_grpc_pb2 as fast__grpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fast_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccessorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResource = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetResource',
                request_serializer=fast__grpc__pb2.ResourceItemRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.ResourceItemResponse.FromString,
                _registered_method=True)
        self.GetResources = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetResources',
                request_serializer=fast__grpc__pb2.ResourcesListRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.ResourcesListResponse.FromString,
                _registered_method=True)
        self.CreateResource = channel.unary_unary(
                '/accessor_service.v1.AccessorService/CreateResource',
                request_serializer=fast__grpc__pb2.ResourceItemCreateRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.ResourceItemResponse.FromString,
                _registered_method=True)
        self.UpdateResource = channel.unary_unary(
                '/accessor_service.v1.AccessorService/UpdateResource',
                request_serializer=fast__grpc__pb2.ResourceItemUpdateRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.ResourceItemResponse.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/accessor_service.v1.AccessorService/DeleteResource',
                request_serializer=fast__grpc__pb2.ResourceDeleteRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAccessRequest = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetAccessRequest',
                request_serializer=fast__grpc__pb2.AccessRequestItemRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.AccessRequestItemSingleResponse.FromString,
                _registered_method=True)
        self.GetAccessesRequest = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetAccessesRequest',
                request_serializer=fast__grpc__pb2.AccessRequestsListRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.AccessRequestsListResponse.FromString,
                _registered_method=True)
        self.CreateAccessRequest = channel.unary_unary(
                '/accessor_service.v1.AccessorService/CreateAccessRequest',
                request_serializer=fast__grpc__pb2.AccessRequestCreateRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.AccessRequestItemSingleResponse.FromString,
                _registered_method=True)
        self.ApproveAccess = channel.unary_unary(
                '/accessor_service.v1.AccessorService/ApproveAccess',
                request_serializer=fast__grpc__pb2.AccessRequestStatusUpdateRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.AccessRequestStatusUpdateResponse.FromString,
                _registered_method=True)
        self.DenyAccess = channel.unary_unary(
                '/accessor_service.v1.AccessorService/DenyAccess',
                request_serializer=fast__grpc__pb2.AccessRequestStatusUpdateRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.AccessRequestStatusUpdateResponse.FromString,
                _registered_method=True)
        self.GetAccountCredentials = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetAccountCredentials',
                request_serializer=fast__grpc__pb2.AccessAccountCredentialsRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.AccessAccountCredentialsResponse.FromString,
                _registered_method=True)
        self.GetResourceAccessAccount = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetResourceAccessAccount',
                request_serializer=fast__grpc__pb2.ResourceAccessAccountItemRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.ResourceAccessAccountItemResponse.FromString,
                _registered_method=True)
        self.GetResourcesAccessAccounts = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetResourcesAccessAccounts',
                request_serializer=fast__grpc__pb2.ResourcesAccessAccountsListRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.ResourcesAccessAccountsListResponse.FromString,
                _registered_method=True)
        self.GetRevoke = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetRevoke',
                request_serializer=fast__grpc__pb2.RevokeRequestItemRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.RevokeRequestItemResponse.FromString,
                _registered_method=True)
        self.GetRevokes = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetRevokes',
                request_serializer=fast__grpc__pb2.RevokeRequestsListRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.RevokeRequestsListResponse.FromString,
                _registered_method=True)
        self.RevokeAccess = channel.unary_unary(
                '/accessor_service.v1.AccessorService/RevokeAccess',
                request_serializer=fast__grpc__pb2.RevokeAccessRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.RevokeRequestItemResponse.FromString,
                _registered_method=True)
        self.Seal = channel.unary_unary(
                '/accessor_service.v1.AccessorService/Seal',
                request_serializer=fast__grpc__pb2.Empty.SerializeToString,
                response_deserializer=fast__grpc__pb2.SealResponse.FromString,
                _registered_method=True)
        self.Unseal = channel.unary_unary(
                '/accessor_service.v1.AccessorService/Unseal',
                request_serializer=fast__grpc__pb2.UnsealRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.UnsealResponse.FromString,
                _registered_method=True)
        self.IsSeal = channel.unary_unary(
                '/accessor_service.v1.AccessorService/IsSeal',
                request_serializer=fast__grpc__pb2.Empty.SerializeToString,
                response_deserializer=fast__grpc__pb2.IsSealResponse.FromString,
                _registered_method=True)
        self.InitStorage = channel.unary_unary(
                '/accessor_service.v1.AccessorService/InitStorage',
                request_serializer=fast__grpc__pb2.InitStorageRequest.SerializeToString,
                response_deserializer=fast__grpc__pb2.InitStorageResponse.FromString,
                _registered_method=True)
        self.GetServiceStatus = channel.unary_unary(
                '/accessor_service.v1.AccessorService/GetServiceStatus',
                request_serializer=fast__grpc__pb2.Empty.SerializeToString,
                response_deserializer=fast__grpc__pb2.ServiceStatusResponse.FromString,
                _registered_method=True)


class AccessorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccessRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccessesRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccessRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DenyAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceAccessAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourcesAccessAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevokes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unseal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsSeal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=fast__grpc__pb2.ResourceItemRequest.FromString,
                    response_serializer=fast__grpc__pb2.ResourceItemResponse.SerializeToString,
            ),
            'GetResources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResources,
                    request_deserializer=fast__grpc__pb2.ResourcesListRequest.FromString,
                    response_serializer=fast__grpc__pb2.ResourcesListResponse.SerializeToString,
            ),
            'CreateResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResource,
                    request_deserializer=fast__grpc__pb2.ResourceItemCreateRequest.FromString,
                    response_serializer=fast__grpc__pb2.ResourceItemResponse.SerializeToString,
            ),
            'UpdateResource': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResource,
                    request_deserializer=fast__grpc__pb2.ResourceItemUpdateRequest.FromString,
                    response_serializer=fast__grpc__pb2.ResourceItemResponse.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=fast__grpc__pb2.ResourceDeleteRequest.FromString,
                    response_serializer=fast__grpc__pb2.Empty.SerializeToString,
            ),
            'GetAccessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccessRequest,
                    request_deserializer=fast__grpc__pb2.AccessRequestItemRequest.FromString,
                    response_serializer=fast__grpc__pb2.AccessRequestItemSingleResponse.SerializeToString,
            ),
            'GetAccessesRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccessesRequest,
                    request_deserializer=fast__grpc__pb2.AccessRequestsListRequest.FromString,
                    response_serializer=fast__grpc__pb2.AccessRequestsListResponse.SerializeToString,
            ),
            'CreateAccessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccessRequest,
                    request_deserializer=fast__grpc__pb2.AccessRequestCreateRequest.FromString,
                    response_serializer=fast__grpc__pb2.AccessRequestItemSingleResponse.SerializeToString,
            ),
            'ApproveAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAccess,
                    request_deserializer=fast__grpc__pb2.AccessRequestStatusUpdateRequest.FromString,
                    response_serializer=fast__grpc__pb2.AccessRequestStatusUpdateResponse.SerializeToString,
            ),
            'DenyAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.DenyAccess,
                    request_deserializer=fast__grpc__pb2.AccessRequestStatusUpdateRequest.FromString,
                    response_serializer=fast__grpc__pb2.AccessRequestStatusUpdateResponse.SerializeToString,
            ),
            'GetAccountCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountCredentials,
                    request_deserializer=fast__grpc__pb2.AccessAccountCredentialsRequest.FromString,
                    response_serializer=fast__grpc__pb2.AccessAccountCredentialsResponse.SerializeToString,
            ),
            'GetResourceAccessAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceAccessAccount,
                    request_deserializer=fast__grpc__pb2.ResourceAccessAccountItemRequest.FromString,
                    response_serializer=fast__grpc__pb2.ResourceAccessAccountItemResponse.SerializeToString,
            ),
            'GetResourcesAccessAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourcesAccessAccounts,
                    request_deserializer=fast__grpc__pb2.ResourcesAccessAccountsListRequest.FromString,
                    response_serializer=fast__grpc__pb2.ResourcesAccessAccountsListResponse.SerializeToString,
            ),
            'GetRevoke': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevoke,
                    request_deserializer=fast__grpc__pb2.RevokeRequestItemRequest.FromString,
                    response_serializer=fast__grpc__pb2.RevokeRequestItemResponse.SerializeToString,
            ),
            'GetRevokes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevokes,
                    request_deserializer=fast__grpc__pb2.RevokeRequestsListRequest.FromString,
                    response_serializer=fast__grpc__pb2.RevokeRequestsListResponse.SerializeToString,
            ),
            'RevokeAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAccess,
                    request_deserializer=fast__grpc__pb2.RevokeAccessRequest.FromString,
                    response_serializer=fast__grpc__pb2.RevokeRequestItemResponse.SerializeToString,
            ),
            'Seal': grpc.unary_unary_rpc_method_handler(
                    servicer.Seal,
                    request_deserializer=fast__grpc__pb2.Empty.FromString,
                    response_serializer=fast__grpc__pb2.SealResponse.SerializeToString,
            ),
            'Unseal': grpc.unary_unary_rpc_method_handler(
                    servicer.Unseal,
                    request_deserializer=fast__grpc__pb2.UnsealRequest.FromString,
                    response_serializer=fast__grpc__pb2.UnsealResponse.SerializeToString,
            ),
            'IsSeal': grpc.unary_unary_rpc_method_handler(
                    servicer.IsSeal,
                    request_deserializer=fast__grpc__pb2.Empty.FromString,
                    response_serializer=fast__grpc__pb2.IsSealResponse.SerializeToString,
            ),
            'InitStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.InitStorage,
                    request_deserializer=fast__grpc__pb2.InitStorageRequest.FromString,
                    response_serializer=fast__grpc__pb2.InitStorageResponse.SerializeToString,
            ),
            'GetServiceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStatus,
                    request_deserializer=fast__grpc__pb2.Empty.FromString,
                    response_serializer=fast__grpc__pb2.ServiceStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accessor_service.v1.AccessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accessor_service.v1.AccessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccessorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetResource',
            fast__grpc__pb2.ResourceItemRequest.SerializeToString,
            fast__grpc__pb2.ResourceItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetResources',
            fast__grpc__pb2.ResourcesListRequest.SerializeToString,
            fast__grpc__pb2.ResourcesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/CreateResource',
            fast__grpc__pb2.ResourceItemCreateRequest.SerializeToString,
            fast__grpc__pb2.ResourceItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/UpdateResource',
            fast__grpc__pb2.ResourceItemUpdateRequest.SerializeToString,
            fast__grpc__pb2.ResourceItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/DeleteResource',
            fast__grpc__pb2.ResourceDeleteRequest.SerializeToString,
            fast__grpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetAccessRequest',
            fast__grpc__pb2.AccessRequestItemRequest.SerializeToString,
            fast__grpc__pb2.AccessRequestItemSingleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccessesRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetAccessesRequest',
            fast__grpc__pb2.AccessRequestsListRequest.SerializeToString,
            fast__grpc__pb2.AccessRequestsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/CreateAccessRequest',
            fast__grpc__pb2.AccessRequestCreateRequest.SerializeToString,
            fast__grpc__pb2.AccessRequestItemSingleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/ApproveAccess',
            fast__grpc__pb2.AccessRequestStatusUpdateRequest.SerializeToString,
            fast__grpc__pb2.AccessRequestStatusUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DenyAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/DenyAccess',
            fast__grpc__pb2.AccessRequestStatusUpdateRequest.SerializeToString,
            fast__grpc__pb2.AccessRequestStatusUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetAccountCredentials',
            fast__grpc__pb2.AccessAccountCredentialsRequest.SerializeToString,
            fast__grpc__pb2.AccessAccountCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceAccessAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetResourceAccessAccount',
            fast__grpc__pb2.ResourceAccessAccountItemRequest.SerializeToString,
            fast__grpc__pb2.ResourceAccessAccountItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourcesAccessAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetResourcesAccessAccounts',
            fast__grpc__pb2.ResourcesAccessAccountsListRequest.SerializeToString,
            fast__grpc__pb2.ResourcesAccessAccountsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetRevoke',
            fast__grpc__pb2.RevokeRequestItemRequest.SerializeToString,
            fast__grpc__pb2.RevokeRequestItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevokes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetRevokes',
            fast__grpc__pb2.RevokeRequestsListRequest.SerializeToString,
            fast__grpc__pb2.RevokeRequestsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/RevokeAccess',
            fast__grpc__pb2.RevokeAccessRequest.SerializeToString,
            fast__grpc__pb2.RevokeRequestItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/Seal',
            fast__grpc__pb2.Empty.SerializeToString,
            fast__grpc__pb2.SealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unseal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/Unseal',
            fast__grpc__pb2.UnsealRequest.SerializeToString,
            fast__grpc__pb2.UnsealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsSeal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/IsSeal',
            fast__grpc__pb2.Empty.SerializeToString,
            fast__grpc__pb2.IsSealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/InitStorage',
            fast__grpc__pb2.InitStorageRequest.SerializeToString,
            fast__grpc__pb2.InitStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accessor_service.v1.AccessorService/GetServiceStatus',
            fast__grpc__pb2.Empty.SerializeToString,
            fast__grpc__pb2.ServiceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
